### ISSUE TITLE
Managing lists

### ISSUE THREAD

**Issue by GHandrea** [asluis/JSON-Hierarchy-Viewer#1]
Hi, on line 51 there's `simple_print(data[0], indents + 1)` which prints **only the first item** of a list... in order to print each item it can be fixed with `simple_print(data[data.index(val)], indents + 1)`.

**Comment by asluis** [comment]
@GHandrea
Thanks for catching this—I have updated the codebase 👍

**Comment by asluis** [comment]
Done
